### PR TITLE
View reposts

### LINKED ISSUE #37: "View reposts" button addon
This addon would add the "View reposts" button from the alpha, also going to a page that is wasteof2 styled.

### PR DESCRIPTION
**Pull request by mybearworld**
Resolves #37

This adds a view reposts button to posts, which when clicked will navigate to ?reposts and show all reposts.

### To Do

- [ ] Compatibility with other addons
- [x] Make my signing stuff work again so the commits don't show up as unverified

### CODE REVIEW

**Comment by mybearworld** [comment]
Regarding addon compatibility, I somehow need to get other addons to run after this addon, which is difficult when all of the important addons here are async

**Comment by imadeanaccount1** [comment]
@mybearworld Feel free to make any (reasonable) changes to the addon-loading system and you may need, such as somehow adding a "loadOrder" field to adodn.jsons that controls the order in which addons are loaded or when they are loaded relative to the page (document's) load status. I don't know, but that's the only solution I can think of.

**Comment by imadeanaccount1** [comment]
how did this get closed???

**Comment by imadeanaccount1** [comment]
here i may have to go through all of the open pull requests and fix them

**Comment by mybearworld** [comment]
I really don't know Git, but from what it looks like you've force transferred the main branch in some way making all PRs outdated?

**Comment by imadeanaccount1** [comment]
@mybearworld I sent this on waste of, but here are some instructions to update your fork with the latest main branch history:

On your local repository:

- Create a new branch in your repo based on the new main branch in the imadeanaccount1/wasteof.plus repo (call it "new_main" or something)

- then, checkout to your actual “main” branch and run: git merge new_main --allow-unrelated-histories

- then, resolve any merge conflicts and complete the merge commit (tell me if you run into any errors!)

- then, create a new branch based on the main branch called "new_view_reposts" (for backup purposes)

- then, in the “"new_view_reposts" branch, run: git merge viewReposts--allow-unrelated-histories

- resolve any merge conflicts in the new_view_reposts branch

Once these steps are complete, your main and new_view_reposts branches should be up-to-date with the most recent changes in the main repo's history. If you run into any problems, let me know and I'll try to help. If not, you can delete the new_main branch when you finish. :)

**Comment by mybearworld** [comment]
I do not, reimplementation coming soon...

**Comment by imadeanaccount1** [comment]
wait, when did you mess up bc i think i have have a local (cloned) version of your fork somewhere.

**Comment by imadeanaccount1** [comment]
@mybearworld does this look like the version you lost?
image

**Comment by imadeanaccount1** [comment]
Okay, i'll create a new repo with the code/files for you! ☺

**Comment by imadeanaccount1** [comment]
@mybearworld i assumed your only changes were to the addons/viewReposts directory, so that's what I copied into this branch. if you had any other files that you had changed that you need me to add to the branch, i can do that too, though!

**Pull request closed without merging**
