### PR TITLE
Polls

### PR DESCRIPTION
**Pull request by mybearworld**
This PR creates a new addon called `polls` which adds the ability to make, view and vote on polls.
Polls
Polls creation post button
The addon in the popup

### CODE REVIEW

**Comment by imadeanaccount1** [comment]
This looks so great :D

**Comment by mybearworld** [comment]
Thank you! 😀

**Comment by imadeanaccount1** [comment]
@mybearworld can you limit the number of times someone can vote?

**Comment by mybearworld** [comment]
Everyone can only vote once. When someone votes twice, only their most recent vote is counted

**Comment by imadeanaccount1** [comment]
is it possible to also not re-post a comment when they vote for the second time, though? i know that it doesn't actually count the vote, but maybe disable the vote button if they've already voted.

**Comment by mybearworld** [comment]
What if the user misvotes accidentally, though?

**Comment by imadeanaccount1** [comment]
they can delete the comment, or you can add an "Unvote" button that deletes the comment for them, right?

**Comment by imadeanaccount1** [comment]
i think that for non-wasteof.plus users, it will be easier to understand the results of a poll if there aren't multiple vote comments. :)

**Comment by imadeanaccount1** [comment]
everything else looks fine, though

**Comment by mybearworld** [comment]
It could automatically delete the comment when you re-vote.

**Review by imadeanaccount1 — CHANGES_REQUESTED** [review]
add unvote button that deletes comments

**Comment by imadeanaccount1** [comment]
do you just want me to merge the PR then?

**Review by imadeanaccount1 — APPROVED** [review]

**Comment by mybearworld** [comment]
These edge cases would really be very difficult to resolve properly. Thank you for merging this, I'm very glad I could contribute to this project!

**Comment by mybearworld** [comment]
@all-contributors please add @mybearworld for code

**Pull request merged**
